import React from 'react';
import { useRouter } from 'next/router';
import BlogStyle from '../../../styles/Blog.module.scss'
import { getCategories, getCategoryPost } from "../../../services"
import { PostCard,PostWidget, Categories, Loader,BlogHeader } from '../../../components';
import Head from 'next/head';

const CategoryPost = ({ posts }) => {
  const router = useRouter();
  
  if (router.isFallback) {
    return <Loader />;
  }

  return (
    <>
    <Head>
        <title>Ariadne Blog |Category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/ariadneicon.png" />
       </Head>
    <BlogHeader/>
    <div className={BlogStyle.blogBody}>
        <div className="container mx-auto px-10 mb-8">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="col-span-1 lg:col-span-8">
          {posts.map((post, index) => (
            <PostCard key={index} post={post.node} />
          ))}
        </div>
        <div className="col-span-1 lg:col-span-4">
          <div className="relative lg:sticky top-8">
          <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
    </div>
    </>
  );
};
export default CategoryPost;

// Fetch data at build time
export async function getStaticProps({ params }) {
  const posts = await getCategoryPost(params.slug);

  return {
    props: { posts },
  };
}

// Specify dynamic routes to pre-render pages based on data.
// The HTML is generated at build time and will be reused on each request.
export async function getStaticPaths() {
  const categories = await getCategories();
  return {
    paths: categories.map(({ slug }) => ({ params: { slug } })),
    fallback: true,
  };
}